
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjvvdpzrjxojyfxmrybi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqdnZkcHpyanhvanlmeG1yeWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjU3MjAsImV4cCI6MjA1ODI0MTcyMH0.M3tbcwFFyjhFCdObLiK28yfRWq20SO0jowWmdtYjfL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
